accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

#app name 명시
#127.0.0.1:8000/account/hello_world
#이걸 항상 쓰기 번거로우니,
#accountapp:hello_world 라고 쓰면 위가 저절로 쓰여짐
from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView, hello_world

app_name = 'accountapp'

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),

    path('login/', LoginView.as_view(template_name ='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),   # int형 pk이름의 변수를 받겠따
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

urlpatterns = [
    path('list/',TemplateView.as_view(template_name='articleapp/list.html'), name='list'),
]

pragmatic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/',ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>',ProfileUpdateView.as_view(), name='update'),

]

accountapp/models.py
from django.db import models

# Create your models here.

class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null = False)

articleapp/models.py
from django.db import models

# Create your models here.

profileapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE, related_name='profile')

    image = models.ImageField('profile/',null=True)
    nickname = models.CharField(max_length=20, unique=True, null = True)
    message = models.CharField(max_length=100, null = True)

accountapp/templates/accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm

class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

profileapp/forms.py
from django.forms import ModelForm

from profileapp.models import Profile


class ProfileCreationForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['image','nickname','message']

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from accountapp.decorators import account_ownership_required
from accountapp.models import HelloWorld


# Create your views here.

##이 뷰를 돌아가게 끔 하기 위해  연결하는 과정(routing: 특정주소를 갔을때) 고로 root.urls.py 에서 연결한다
from accountapp.templates.accountapp.forms import AccountUpdateForm

has_ownership = [account_ownership_required, login_required]


'''
@login_required  
    if request.user.is_authenticated:     
    
    else :
        return HttpResponseRedirect(reverse('accountapp:login'))
        
    을 decorating한다.


'''
@login_required
def hello_world(request):

    if request.method =="POST":

        temp = request.POST.get('hello_world_input')

        new_hello_world = HelloWorld()
        new_hello_world.text = temp
        new_hello_world.save() #DB 저장

        return HttpResponseRedirect(reverse('accountapp:hello_world'))

    else :
        hello_world_list = HelloWorld.objects.all()  # 이러면 모든 객체를 다 긁어온다.
        return render(request, 'accountapp/hello_world.html', context ={'hello_world_list':hello_world_list})



class AccountCreateView(CreateView) :
    model = User
    form_class = UserCreationForm  #장고가 유저 계정정보 폼을 제공한다.
    success_url = reverse_lazy('accountapp:hello_world')  #어디로 연결할건지 설정한다
    template_name = 'accountapp/create.html'


    '''
    redirect함수 인 reverse, 와 reverse_lazy는 함수와 클래스 차이이기때문
    '''

class AccountDetailView(DetailView) :
    model = User
    context_object_name= 'target_user'
    template_name = 'accountapp/detail.html'


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView) :
    model = User
    context_object_name = 'target_user'
    form_class = AccountUpdateForm  #장고가 유저 계정정보 폼을 제공한다.
    success_url = reverse_lazy('accountapp:hello_world')  #어디로 연결할건지 설정한다
    template_name = 'accountapp/update.html'


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'


    '''
    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated and self.get_object() == self.request.user:
            return super().get(*args, **kwargs)
        else :
            return HttpResponseForbidden()

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated and self.get_object() == self.request.user:
            return super().post(*args, **kwargs)
        else:
            return HttpResponseForbidden()
    
    '''

articleapp/views.py
from django.shortcuts import render

# Create your views here.

profileapp/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView

from profileapp.decorators import profile_ownership_required
from profileapp.forms import ProfileCreationForm
from profileapp.models import Profile


class ProfileCreateView(CreateView):
    model = Profile
    context_object_name = 'target_profile'
    form_class = ProfileCreationForm
    template_name = 'profileapp/create.html'

    def form_valid(self, form):
        temp_profile = form.save(commit=False)    ##user form 저장
        temp_profile.user = self.request.user     ##request user를 그대로 대입해서
        temp_profile.save()   ## 그대로 저장

        return super().form_valid(form)  ##그대로 함수반환

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk': self.object.user.pk})


@method_decorator(profile_ownership_required, 'get')
@method_decorator(profile_ownership_required, 'post')
class ProfileUpdateView(UpdateView) :
    model = Profile
    context_object_name = 'target_profile'
    form_class = ProfileCreationForm  #장고가 유저 계정정보 폼을 제공한다.
    template_name = 'profileapp/update.html'

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk': self.object.user.pk})

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>SignUp</h4>
        </div>
        <form action = "{% url 'accountapp:create' %}" method="post"> <!--액션을 보내는 url이 필요 -->
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>

{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Quit</h4>
        </div>
        <form action = "{% url 'accountapp:delete' pk=target_user.pk %}" method="post"> <!--액션을 보내는 url이 필요 -->
            {% csrf_token %}
            <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
        </form>
    </div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}


    <div>
        <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
            <p>
                {{ target_user }}
                {{ user }}
                {{ target_user.date_joined }}
            </p>


            {% if target_user.profile %}
            <img src="{{ target_user.profile.image.url }}" alt=""
                 style="height: 12rem; width: 12rem; border-radius: 20rem; margin-bottom: 2rem;">

            <h2 style="font-family: 'NanumSquareB'">
                {{ target_user.profile.nickname }}
                    {% if target_user == user %}
                    <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
                        edit
                    </a>
                    {% endif %}
            </h2>
            <h5 style="margin-bottom: 4rem;">
                {{ target_user.profile.message }}
            </h5>
            {% else %}

                {% if target_user == user %}
                <a href="{% url 'profileapp:create' %}">
                    <h2 style="font-family: 'NanumSquareB'">
                        Create Profile
                    </h2>
                </a>
                {% else %}
                <h2>
                    닉네임 미설정
                </h2>
                {% endif %}
            {% endif %}


            {% if target_user == user %}
            <a href="{% url 'accountapp:update' pk=user.pk %}">
                <p>
                    Change Info
                </p>
            </a>
            <a href="{% url 'accountapp:delete' pk=user.pk %}">
                <p>
                    Quit
                </p>
            </a>
            {% endif %}

        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}

{% block content %}
    <div style = 'border-radius; margin: 2rem; text-align: center'>
        <h1 style="font-family: 'Staatliches', cursive'"> <!--steatlitch가 없으면 sursive를 사용하라는 의미-->
            Hello World LIST!
        </h1>

        <form action="/account/hello_world/" method="post">
            {% csrf_token %}
            <div>
                <input type="text" name="hello_world_input">
            </div>
            <div>
                <input type="submit" class="btn btn-primary" value="POST">
            </div>

        </form>

        {% if hello_world_list %}
            {% for hello_world in hello_world_list %}
            <h4>
                {{ hello_world.text }}
            </h4>
            {% endfor %}
        {% endif %}

    </div>


{% endblock %}



<!--

        {% if hello_world_output %}
        <h1>
            {{ hello_world_output.text }}
        </h1>
        {% endif %}



    <style>
        .testing{
            background-color: white;
            height : 3rem;
            width: 3rem;
            margin: 1rem;
        }
    </style>

    <div style = 'height: 20rem; background-color: #38df81; border-radius; margin: 2rem; font-size: 2rem'>
        <h1>
            testing
        </h1>

        <div class="testing" style="display: inline-block; width: 48px ; height: 48px">block</div>
        <div class="testing" style="display: inline-block; width: 3em ; height: 3em">block</div>
        <div class="testing" style="display: inline-block; width: 3rem ; height: 3rem">block</div>
        <div class="testing" style="display: inline-block; width: 30% ; height: 30%">block</div>

        <div class="testing" style="display: block;">block</div>
        <div class="testing" style="display: inline;">inline</div>
        <div class="testing" style="display: None;">None</div>
        <div class="testing" style="display: inline-block;">inline-block</div>
        <div class="testing"> default</div>

    </div>

-->

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style = "text-align: center; max-width: 500px; margin: 4rem auto">
        <div>
            <h4>Login</h4>
        </div>
        <div>
            <form action="" method="post">
                {% csrf_token %}
                <!--{{ form }}-->
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
            </form>

        </div>

    </div>

{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Change Info</h4>
        </div>
        <form action = "{% url 'accountapp:update' pk=target_user.pk %}" method="post"> <!--액션을 보내는 url이 필요 -->
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>

{% endblock %}

articleapp/templates/articleapp/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<style>
    .container div {
      width: 250px;
      background-color: antiquewhite;
      display: flex;
      justify-content: center;
      align-items: center;
      border-radius: 1rem;
    }

    .container img {
      width: 100%;
      border-radius: 1rem;
    }

</style>

    <div class="container">
       <div class="item1">
        <img src="https://picsum.photos/200/300" alt="">
       </div>
       <div >
        <img src="https://picsum.photos/200/340" alt="">
       </div>
       <div >
        <img src="https://picsum.photos/200/260" alt="">
       </div>
       <div >
        <img src="https://picsum.photos/200/300" alt="">
       </div>
       <div >
        <img src="https://picsum.photos/200/510" alt="">
       </div>
       <div >
        <img src="https://picsum.photos/200/280" alt="">
       </div>
       <div >
        <img src="https://picsum.photos/200/400" alt="">
       </div>
       <div >
        <img src="https://picsum.photos/200/320" alt="">
       </div>
       <div >
        <img src="https://picsum.photos/200/250" alt="">
       </div>
       <div >
        <img src="https://picsum.photos/200/220" alt="">
       </div>
       <div >
        <img src="https://picsum.photos/200/240" alt="">
       </div>
       <div >
        <img src="https://picsum.photos/200/260" alt="">
       </div>
       <div >
        <img src="https://picsum.photos/200/280" alt="">
       </div>
    </div>

    <script src="{% static 'js/magicgrid.js' %}"></script>
{% endblock %}

profileapp/templates/profileapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Profile Create</h4>
        </div>
        <form action = "{% url 'profileapp:create' %}" method="post" enctype="multipart/form-data" > <!--액션을 보내는 url이 필요 -->
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>

{% endblock %}

profileapp/templates/profileapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Update Profile</h4>
        </div>
        <form action = "{% url 'profileapp:update' pk=target_profile.pk %}" method="post" enctype="multipart/form-data"> <!--액션을 보내는 url이 필요 -->
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body style="font-family: 'NanumSquareR';">

    {% include 'header.html' %}

    <hr>

    {% block content %}
    {% endblock %}

    <hr>

    {% include 'footer.html' %}

</body>
</html>

templates/footer.html
    <div class="pragmatic_footer">
        <div class="pragmatic_footer_button">
            <span>공지사항</span> |
            <span>제휴문의</span> |
            <span>서비스 소개</span>
        </div>
        <div style="margin-top: 1rem">
            <h6 class="pragmatic_logo" > Pragmatic</h6>
        </div>

    </div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>pragmatic</title>

    <!-- BOOTSTRAP LINK-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <!--Font style-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Staatliches&display=swap" rel="stylesheet">

    <!-- DEFAULT CSS LINK-->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    <!--FONT LOAD-->
    <style>
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareL';
            src: local('NanumSquareL'),
            url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype");
        }
    </style>
</head>

templates/header.html
    <div class="pragmatic_header">
        <div>
            <h1 class="pragmatic_logo" >Pragmatic</h1>
        </div>
        <div>
            <span>nav1</span>
            <span>nav2</span>
            <span>nav3</span>
            {% if not user.is_authenticated %}
            <a href="{% url 'accountapp:login' %}?next={{ request.path }}">
                <span>Login</span>
            </a>
             <a href="{% url 'accountapp:create' %}">
                <span>SignUp</span>
            </a>
            {% else %}
            <a href="{% url 'accountapp:detail' pk=user.pk %}">
                <span>MyPage</span>
            </a>
            <!--
            <a href="{% url 'accountapp:logout' %}?next={{ request.path }}">
            -->
            <a href="{% url 'accountapp:logout' %}?next={{ request.path }}">
                <span>Logout</span>
            </a>
            {% endif %}
        </div>

    </div>